# Generated by Django 6.1 on 2026-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodName', '0005_foodreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '⭐ 1 Star'), (2, '⭐⭐ 2 Stars'), (3, '⭐⭐⭐ 3 Stars'), (4, '⭐⭐⭐⭐ 4 Stars'), (5, '⭐⭐⭐⭐⭐ 5 Stars')]),
        ),
    ]
