# Generated by Django 6.1 on 2026-09-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodName', '0006_alter_foodreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='FoodName.fooditem'),
        ),
    ]
