# Generated by Django 6.1 on 2026-09-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodName', '0011_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.CharField(blank=True, help_text='Example: Pizza, Burger. Leave blank for all categories.', max_length=100, null=True),
        ),
    ]
